# TENSOR
   the tensor is a maping of the elements in order to define the dimension size and shape 

## 0 D tensor

In [1]:
import numpy as np





In [ ]:
D0=np.array(0)

print("element:",D0)
print ("dimension of the tensor :",D0.ndim)

element: 0
dimension of the tensor : 0


## 1 D tensor 
vector

In [8]:
D1=np.array([1,2,3,4,5,6])

print("element:",D1)
print ("dimension of the tensor :",D1.ndim)

element: [1 2 3 4 5 6]
dimension of the tensor : 1


## 2 D tensor

In [15]:
D2=np.array([[1,2,3,4],[2,3,4,8]])

print("element:",D2)
print ("dimension of the tensor :",D2.ndim)

element: [[1 2 3 4]
 [2 3 4 8]]
dimension of the tensor : 2


In [14]:
random_array = np.random.rand(4, 5)

# Method C: Manually defining values
manual_array = np.array([
    [1, 2, 3, 4, 5],
    [6, 7, 8, 9, 10],
    [11, 12, 13, 14, 15],
    [16, 17, 18, 19, 20]
])

random_array

array([[0.60826292, 0.46547609, 0.59974129, 0.38199889, 0.1794027 ],
       [0.77403512, 0.36128782, 0.40553025, 0.82056662, 0.12224767],
       [0.9087213 , 0.97493599, 0.02849615, 0.0054316 , 0.54925267],
       [0.37024261, 0.74063195, 0.59980146, 0.15904778, 0.2434467 ]])

## 3 D tensor 
graphs 

In [21]:
random_array = np.random.rand(2,5,2)




d3=np.array([[[1,2,3,4,5],
              [1,2,3,4,5],
              [1,2,3,4,5],
              [1,2,3,4,5]],
              [[1,2,3,4,5],
              [1,2,3,4,5],
              [1,2,3,4,5],
              [1,2,3,4,5]]
              ])



print("element:",d3)
print ("dimension of the tensor :",d3.ndim)

element: [[[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]

 [[1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]
  [1 2 3 4 5]]]
dimension of the tensor : 3


## 4 D TENSORS

image proccessing

In [25]:
random_array = np.random.rand(2,2,5,2)
print(random_array)

print("dimension of the array:",random_array.ndim)



[[[[0.31508462 0.59942655]
   [0.76241047 0.76554008]
   [0.51647369 0.33474721]
   [0.27181128 0.59387147]
   [0.29862701 0.84615844]]

  [[0.99221158 0.31011331]
   [0.3689528  0.80843447]
   [0.80605141 0.17991642]
   [0.16938266 0.41734916]
   [0.78053544 0.62296941]]]


 [[[0.38128409 0.43665937]
   [0.39494939 0.49630466]
   [0.6370619  0.29618484]
   [0.13025803 0.29365943]
   [0.5626456  0.35792728]]

  [[0.23793781 0.63162136]
   [0.70230825 0.46277735]
   [0.00732361 0.15236485]
   [0.33678705 0.58429488]
   [0.85909352 0.71743939]]]]
dimension of the array: 4


## 5 D tensor 

using mostly for the vedio capturing 

In [26]:
random_array = np.random.rand(2,2,2,5,2)
print(random_array)

print("dimension:",random_array.ndim)

[[[[[0.76055052 0.34592958]
    [0.04037874 0.36313335]
    [0.58902882 0.77236692]
    [0.5801077  0.90287386]
    [0.3368234  0.68606979]]

   [[0.10945259 0.26904142]
    [0.41920318 0.62259844]
    [0.79512914 0.34375948]
    [0.90189628 0.41242325]
    [0.88994252 0.1899877 ]]]


  [[[0.50932668 0.15073114]
    [0.25341607 0.43814925]
    [0.72547101 0.41032399]
    [0.55320962 0.62134542]
    [0.84608108 0.57294498]]

   [[0.38703989 0.39641982]
    [0.71806697 0.22147563]
    [0.40440335 0.62549951]
    [0.52640799 0.10234438]
    [0.31252897 0.62615635]]]]



 [[[[0.06530797 0.78653733]
    [0.74408454 0.88769682]
    [0.56894885 0.74861847]
    [0.93632313 0.73918167]
    [0.05809348 0.81801874]]

   [[0.25951143 0.69654823]
    [0.41646993 0.86151682]
    [0.16844939 0.7984121 ]
    [0.57757135 0.01267269]
    [0.99823974 0.71351949]]]


  [[[0.20836923 0.63778881]
    [0.90347741 0.33072426]
    [0.28580596 0.11759121]
    [0.87720002 0.74078269]
    [0.28159463 0.03879574]]